// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGSGm2Ju9fk4c2Kz5LyTivr22gK-JyWB0',
    appId: '1:630327568157:android:5863a9bedc8be94b7f23f4',
    messagingSenderId: '630327568157',
    projectId: 'dental001-c667f',
    databaseURL: 'https://dental001-c667f-default-rtdb.firebaseio.com',
    storageBucket: 'dental001-c667f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1_DmRT8_-tjZ6chGhOSYHY11TGpr8d_g',
    appId: '1:630327568157:ios:7e001b15e1aa79de7f23f4',
    messagingSenderId: '630327568157',
    projectId: 'dental001-c667f',
    databaseURL: 'https://dental001-c667f-default-rtdb.firebaseio.com',
    storageBucket: 'dental001-c667f.appspot.com',
    androidClientId: '630327568157-8lmlb19ltj7nl5ps1k4lgs3rhb5sdikp.apps.googleusercontent.com',
    iosClientId: '630327568157-qmt32ho0jeepmghhlte0b45ne5cula2h.apps.googleusercontent.com',
    iosBundleId: 'com.example.dentalapp',
  );
}
